### ISSUE TITLE
Move attribute definitions to inspec.yml as per the new style

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-sql-2014-server-stig-baseline#3]
# Profile Attributes

Attributes are frequently used to parameterize a profile for use in different environments or targets. It can also be used define secrets, such as user names and passwords, that should not otherwise be stored in plain-text in a cookbook. Attributes may be set for the whole profile in the `inspec.yml`.

Attributes may contain the following options:

* Use `default` to set a default value for the attribute.
* Use `type` to restrict an attribute to a specific type (any, string, numeric, array, hash, boolean, regex).
* Use `required` to mandate the attribute has a default value or a value from a attribute YAML file.
* Use `description` to set a brief description for the attribute.

You can specify attributes in your `inspec.yml` using the `attributes` setting. For example, to add a `user` attribute for your profile:

```YAML
attributes:
  - name: user
    type: string
    default: bob
```

Example of adding a array object of servers:

```YAML
attributes:
  - name: servers
    type: array
    default:
      - server1
      - server2
      - server3
```

To access an attribute you will use the `attribute` keyword. You can use this anywhere in your control code.

For example:

```Ruby
current_user = attribute('user')

control 'system-users' do
  describe attribute('user') do
    it { should eq 'bob' }
  end

  describe current_user do
    it { should eq attribute('user') }
  end
end
```

For sensitive data it is recomended to use a secrets YAML file located on the local machine to populate the values of attributes. A secrets file will always overwrite a attributes default value. To use the secrets file run `inspec exec` and specify the path to that Yaml file using the `--attrs` attribute.
